# Generated by Django 4.1.2 on 2022-10-29 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "match_id",
                    models.IntegerField(
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="比赛ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="当季比赛", max_length=256, verbose_name="比赛名称"
                    ),
                ),
                ("opponent_id", models.CharField(max_length=64, verbose_name="对方队伍ID")),
                (
                    "outcome",
                    models.IntegerField(
                        choices=[[0, "win"], [1, "loss"], [2, "tie"]],
                        verbose_name="比赛结果",
                    ),
                ),
                ("ownScore", models.IntegerField(default=0, verbose_name="队伍进球数")),
                ("opponentScore", models.IntegerField(default=0, verbose_name="对手进球数")),
                (
                    "side",
                    models.IntegerField(
                        choices=[[0, "home"], [1, "away"]], verbose_name="比赛队伍身份"
                    ),
                ),
                ("coach_id", models.CharField(max_length=64, verbose_name="教练身份码")),
            ],
            options={"verbose_name_plural": "比赛", "db_table": "Match",},
        ),
        migrations.CreateModel(
            name="PassingEvents",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("team_id", models.CharField(max_length=64, verbose_name="团队ID")),
                (
                    "origin_player_id",
                    models.CharField(max_length=64, verbose_name="起始球员身份"),
                ),
                (
                    "destination_player_id",
                    models.CharField(max_length=64, verbose_name="目的球员身份"),
                ),
                (
                    "match_period",
                    models.IntegerField(
                        choices=[[0, "1H"], [1, "2H"]], verbose_name="比赛进行阶段"
                    ),
                ),
                ("event_time", models.FloatField(verbose_name="比赛时间")),
                (
                    "event_sub_type",
                    models.IntegerField(
                        choices=[
                            [0, "Head pass"],
                            [1, "Simple pass"],
                            [2, "Launch"],
                            [3, "High pass"],
                            [4, "Hand pass"],
                            [5, "Smart pass"],
                            [6, "Cross"],
                        ],
                        verbose_name="传球类型",
                    ),
                ),
                ("event_origin_x", models.IntegerField(verbose_name="起始球员位置X")),
                ("event_origin_y", models.IntegerField(verbose_name="起始球员位置Y")),
                ("event_destination_x", models.IntegerField(verbose_name="目的球员位置X")),
                ("event_destination_y", models.IntegerField(verbose_name="目的球员位置Y")),
                (
                    "match_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tream.match",
                        verbose_name="比赛ID",
                    ),
                ),
            ],
            options={"verbose_name_plural": "各种传球过程", "db_table": "PassingEvents",},
        ),
    ]
