# Generated by Django 4.1.2 on 2022-11-11 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tream", "0004_footballtream"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="home_name",
            field=models.CharField(
                default="Huskies", max_length=64, verbose_name="己方球队队伍"
            ),
        ),
    ]
