# Generated by Django 4.1.2 on 2022-11-15 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tream", "0005_match_home_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="footballtream",
            name="area",
            field=models.CharField(default=1, max_length=256, verbose_name="所属地区"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="footballtream",
            name="chairman",
            field=models.CharField(default=1, max_length=256, verbose_name="主席"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="footballtream",
            name="famous_person",
            field=models.CharField(default=1, max_length=1024, verbose_name="知名人物"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="footballtream",
            name="founding_time",
            field=models.CharField(default=1, max_length=256, verbose_name="成立时间"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="footballtream",
            name="home_hall",
            field=models.CharField(default=1, max_length=256, verbose_name="主场馆"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="footballtream",
            name="main_honor",
            field=models.CharField(default=1, max_length=1024, verbose_name="主要荣誉"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="footballtream",
            name="owner",
            field=models.CharField(default=11, max_length=256, verbose_name="拥有者"),
            preserve_default=False,
        ),
    ]
