# Generated by Django 4.1.2 on 2022-11-15 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tream", "0006_footballtream_area_footballtream_chairman_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="footballtream",
            name="tream_history",
            field=models.TextField(default=1, verbose_name="球队历史"),
            preserve_default=False,
        ),
    ]
