# Generated by Django 4.1.2 on 2022-11-08 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_alter_newuser_coa"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coach",
            name="phone",
            field=models.CharField(max_length=256, verbose_name="电话号码"),
        ),
    ]
