# Generated by Django 4.1.2 on 2022-11-09 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_alter_coach_phone"),
    ]

    operations = [
        migrations.RemoveField(model_name="newuser", name="coa",),
        migrations.AddField(
            model_name="newuser",
            name="tream_emblem",
            field=models.ImageField(
                default="default.jpg", upload_to="tream", verbose_name="团队队徽"
            ),
        ),
        migrations.AlterField(
            model_name="newuser",
            name="roles",
            field=models.IntegerField(
                choices=[[0, "admin"], [1, "user"], [2, "coach"]],
                default=1,
                verbose_name="角色",
            ),
        ),
        migrations.DeleteModel(name="Coach",),
    ]
