# Generated by Django 4.1.2 on 2022-11-14 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_remove_newuser_tream_emblem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newuser",
            name="position",
            field=models.CharField(
                choices=[
                    ["0", "中锋"],
                    ["1", "边锋"],
                    ["2", "前腰"],
                    ["3", "后腰"],
                    ["4", "中前卫"],
                    ["5", "左前卫"],
                    ["6", "右前卫"],
                    ["7", "中后卫"],
                    ["8", "左后卫"],
                    ["9", "右后卫"],
                    ["10", "门将"],
                ],
                max_length=32,
                null=True,
                verbose_name="位置",
            ),
        ),
    ]
