# Generated by Django 4.1.2 on 2022-11-17 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0006_alter_newuser_position"),
    ]

    operations = [
        migrations.RemoveField(model_name="newuser", name="body",),
        migrations.RemoveField(model_name="newuser", name="control",),
        migrations.RemoveField(model_name="newuser", name="defend",),
        migrations.RemoveField(model_name="newuser", name="score",),
        migrations.RemoveField(model_name="newuser", name="speed",),
        migrations.AddField(
            model_name="newuser",
            name="join_time",
            field=models.FloatField(default=0, verbose_name="上场时长"),
        ),
        migrations.AddField(
            model_name="newuser",
            name="run_distance",
            field=models.FloatField(default=0, verbose_name="跑动距离"),
        ),
        migrations.AddField(
            model_name="newuser",
            name="speed_num",
            field=models.FloatField(default=0, verbose_name="加速次数"),
        ),
        migrations.AddField(
            model_name="newuser",
            name="sprint_distance",
            field=models.FloatField(default=0, verbose_name="冲刺距离"),
        ),
    ]
