# Generated by Django 4.1.2 on 2022-11-17 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0007_remove_newuser_body_remove_newuser_control_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newuser",
            name="join_time",
            field=models.FloatField(default=0, verbose_name="上场时长(分钟)"),
        ),
        migrations.AlterField(
            model_name="newuser",
            name="run_distance",
            field=models.FloatField(default=0, verbose_name="跑动距离(公里)"),
        ),
        migrations.AlterField(
            model_name="newuser",
            name="sprint_distance",
            field=models.FloatField(default=0, verbose_name="冲刺距离(公里)"),
        ),
    ]
