# Generated by Django 4.1.2 on 2022-11-17 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0008_alter_newuser_join_time_alter_newuser_run_distance_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="newuser",
            name="heart_avg",
            field=models.FloatField(default=70, verbose_name="平均心率"),
        ),
        migrations.AddField(
            model_name="newuser",
            name="sprint_num",
            field=models.FloatField(default=0, verbose_name="冲刺次数"),
        ),
    ]
